PingCAP-QE/tirelease

- website/src/components/tifc/CIColumnsGrid.js
- change first introducer to possible introducer for better understanding
> change first introducer to possible introducer for better understanding

- website/src/components/tifc/CIColumnsGrid.js
> add new column affected prs

- internal/repository/issue_affect.go
- internal/service/issue_affect.go
1.fix: affect and may-affect circle operate status sync
> Backend allapi

- internal/service/issue_relation_info_local.go
> fixme: npe of pull_request inserts

- commons/database/mysql.go
1.fixme: mysql connect time_zone to local
> fixme: mysql time_zone to local

- commons/database/mysql.go
- internal/controller/issue_relation_info.go
- internal/dto/issue_relation_info.go
- internal/repository/release_version_test.go
- internal/service/issue_affect.go
- internal/service/issue_affect_test.go
- internal/service/issue_relation_info_local.go
- internal/service/issue_relation_info_test.go
- internal/service/webhook_issue_test.go
1.fixme: shouldBindJson and form data;
2.database connects pool;
3.ops: select release_versions only once;
> Optimize: Performance Of SelectIssue

- internal/controller/issue_relation_info.go
- internal/entity/issue_affect.go
- internal/entity/pull_request.go
- internal/repository/issue.go
- internal/repository/issue_affect.go
- internal/repository/issue_test.go
- internal/repository/pull_request.go
- internal/repository/pull_request_test.go
- internal/service/issue_relation_info_local.go
- internal/service/webhook_pull_request.go
1.add: performance 100% upgrade hahaha by join and batch select & test OK
> add: performance 100% upgrade hahaha by join and batch select & test OK

- internal/controller/issue_relation_info.go
- internal/entity/common_option.go
- internal/entity/issue.go
- internal/repository/issue.go
- internal/repository/issue_relation_info.go
- internal/repository/release_version_test.go
- internal/service/issue_relation_info_local.go
- internal/service/issue_relation_info_test.go
- internal/service/version_triage_info.go
1.[add: pagenation return](https://github.com/VelocityLight/tirelease/commit/2b15049577d5a442cc4532975b71a1544d6a70d3)
> add: pagenation return

- internal/controller/issue_relation_info.go
- internal/dto/issue_relation_info.go
- internal/entity/common_option.go
> add timestamp support

- website/src/components/tifc/CIData.js
- website/src/components/tifc/CITable.js
> update unstable test url

- website/src/components/version/VersionTableColumns.js
ops: version page add release_branch
> ops: version page add release_branch

- api/api.go
- internal/controller/version_triage.go
- internal/service/version_triage_info.go
1.add: update version_triage api
> add: update version_triage api

- commons/configs/config_test.go
- internal/controller/webhook_github.go
- internal/service/webhook_issue.go
- internal/service/webhook_issue_test.go
- internal/service/webhook_pull_request.go
1. add: pr ref issue;
2. data implement: fill release-6.0 version triage
> Ops refactor

- website/src/components/issues/renderer/PullRequest.js
1.fixme: one issue ref multi prs show
> fixme: one issue ref multi prs

- internal/service/release_version_test.go
- website/src/components/issues/filter/FilterDialog.js
- website/src/components/release/ReleaseTable.js
- website/src/components/release/fetchVersionIssue.js
- website/src/pages/release.js
Issue Number: close #94 
由于筛选能力在后端实现对整体结构影响较大，目前先在前端进行筛选处理。后续结合重构后整体情况决定是否修改
- 给每个FilterDialog元素增加filter变量
- 传入参数params的类型要求为 issue
> +: Version Triage页面添加筛选功能

- website/src/components/issues/filter/FilterDialog.js
- website/src/components/release/ReleaseTable.js
- website/src/pages/release.js
> Add Close Time and Create Time to Version Triage Plane

- website/src/components/issues/filter/FilterDialog.js
- website/src/components/issues/renderer/PickTriage.js
- website/src/components/release/ReleaseTable.js
- website/src/pages/release.js
Issue Number: close #108 
在VersionTriage页面的筛选面板添加TriageResult和TriageStatus选项
效果如下
> Add Triage Status and Triage Result to the filter of Version Triage Plane

- internal/entity/issue.go
- internal/entity/pull_request.go
- internal/repository/issue.go
- internal/service/component/component_mapper.go
- internal/service/component/component_mapper_test.go
- internal/service/version_triage_info_test.go
- website/src/components/issues/GridColumns.js
- website/src/components/issues/filter/FilterDialog.js
- website/src/pages/all.js
- website/src/pages/release.js
Issue Number: close #112 
- 由于目前components规范没有统一，因此不进行持久化，仅在查询时进行返回。
- All Issues页面暂时不提供components筛选，因为该页面的筛选在后端进行，改造成本较高
> Add components granularity

- internal/repository/release_version.go
Issue Number: close #114 
Add logic to cover the condition that the request does not contain a shottype
> Hotfix for ShortType logic flaws

- deployments/kubernetes/ingress.yaml
Follow [kubernetes \- getting error unable to recognize "ingress\.yaml": no matches for kind "Ingress" in version "extensions/v1beta1 \- Stack Overflow](https://stackoverflow.com/questions/71580786/getting-error-unable-to-recognize-ingress-yaml-no-matches-for-kind-ingress)
> update ingress to networking.k8s.io/v1

- website/src/components/issues/GridColumns.js
> Make export of Issue Number take url

- website/src/components/issues/renderer/Affection.js
- website/src/components/issues/renderer/PickTriage.js
Issue Number: close #121 
Caused by the front-end component doesn't refresh the variable value of parent components
> Issue fix: value of items are not rendered at expected way.

- website/src/components/issues/GridColumns.js
- website/src/pages/all.js
Issue Number: close #124 
Because of MUI-free's limitation, the Number item can not support the Filter and Exporter well.
> Decouple issue number and issue url

- website/src/components/issues/renderer/PickTriage.js
> Issue Fix: push new element while there is no data for the version triage

- internal/controller/issue_relation_info.go
- internal/entity/version_triage.go
- internal/service/issue_relation_info_local.go
- internal/service/issue_relation_info_test.go
- internal/service/version_triage_info.go
- internal/service/webhook_issue.go
- website/src/components/issues/GridColumns.js
- website/src/components/issues/filter/FilterDialog.js
- website/src/components/issues/renderer/PickTriage.js
- website/src/components/release/ReleaseTable.js
- website/src/pages/all.js
- website/src/pages/release.js
Issue Number: close #131 
- Review by commits is recommened
- Refactor is done mainly toward method FindIssueRelationInfo
- Tested by UI because there is few additional logic change.
> Add Fixed Lower  to Version Triage Plane (with some refactors)

- go.mod
- internal/service/fsm/fsm_test.go
- internal/service/fsm/interface.go
- internal/service/fsm/template.go
Issue Number: close #133 
see: [TiReleaseFSM技术方案设计 \- 飞书云文档](https://pingcap.feishu.cn/wiki/wikcnR18wQbl7XrRNQMsiEKZUcg)
> Refactor fsm

- internal/service/component/component_mapper.go
- website/src/components/issues/GridColumns.js
- website/src/components/issues/filter/FilterDialog.js
- add new components to TiDB repo
- optimize the component filter to selector.
> Add tidb components & optimize the front-end

- .gitignore
- README.md
- api/api.go
- commons/git/client_testdata.go
- commons/git/restful_api.go
- commons/git/restful_api_test.go
- internal/controller/user.go
- internal/controller/user_application.go
- internal/controller/user_vo.go
- internal/service/git_antisepsis.go
- internal/service/user.go
- website/package.json
- website/src/components/common/LocalStorage.js
- website/src/components/common/Login.js
- website/src/config.js
- website/src/layout/LoginListItem.js
- website/src/layout/Orders.js
- website/src/layout/Sidebar.js
- website/src/routes.js
Issue Number: close #148 ,close #147 
Add user manual book : just like the img above.
Add git sso login:
- Login using git clien_id and client_secret
- **client_id and client_secret are stored in  website/src/config.js locally and should never be pushed to repo.**
- The frontend stores the user info using **storage** pkg.
- The backend using git **restful api** to fetch the user token and user information because of the lack api in git v3/v4 client.
- ref: [https://github\.com/login/oauth/authorize?client\_id=](https://developer.aliyun.com/article/939797)
> Feature: add user manual book & git sso login 

- cmd/tirelease/main.go
- commons/git/restful_api_test.go
- internal/cron/init_cron.go
- internal/entity/task.go
- internal/repository/task.go
- internal/repository/task_test.go
- internal/task/cron_creation.go
- internal/task/cron_creation_test.go
- internal/task/execution_base.go
- internal/task/execution_base_test.go
- internal/task/refresh_employee_execution.go
- internal/task/refresh_issue_execution.go
- internal/task/refresh_pr_execution.go
Issue Number: close #152 
Task Creation:
- Use cron to create tasks in fixed interval.
- Use UniqueMeta to avoid creation duplication.
Task Execution:
- Use template Pattern to avoid code redundancy.
- Use transaction to ensure data consistency.
> Feature( task queue ): add task queue function to execute some tasks only once.

- cmd/tirelease/main.go
- commons/configs/config.go
- config_example.yaml
- internal/entity/employee.go
- internal/repository/employee.go
- internal/repository/hr_employee.go
- internal/repository/hr_employee_test.go
- internal/task/execution_base.go
- internal/task/refresh_employee_execution.go
Issue Number: close #154 
Fetch data from hr_employees table got from data department and refresh tirelease's db every half day.
> dev(db): refresh employee data in fixed interval

- internal/entity/employee.go
- internal/entity/issue.go
- internal/repository/employee.go
- internal/repository/employee_test.go
- internal/service/issue_db_transfer.go
- internal/service/issue_db_transfer_test.go
- internal/service/issue_relation_info_local.go
- website/src/components/issues/renderer/Assignee.js
Issue Number: close #156 
Because there is not an isolated userVO or user model, I have to maintain the employee information in the issue entity which will be refactored later.
> feature(user): replace the user github login with user name

- internal/entity/release_version.go
- internal/service/release_version.go
- website/src/components/common/LocalStorage.js
- website/src/components/issues/GridColumns.js
- website/src/components/issues/IssueGrid.js
- website/src/components/issues/fetcher/fetchVersion.js
- website/src/components/issues/renderer/Affection.js
- website/src/components/issues/renderer/PickSelect.js
- website/src/components/issues/renderer/PickTriage.js
- website/src/components/issues/renderer/mapper.js
- website/src/pages/affects.js
- website/src/pages/all.js
- website/src/pages/close.js
- website/src/pages/open.js
- website/src/pages/release.js
- website/src/utils.js
Issue Number: close #166 
- In the following situation , the triage status will be approved(frozen)
- the related version is frozen and the original triage result is not "approved"
- query version response before PickTriage component for user experience.(the page will render faster.)
> feature( triage ): change the triage selector from approved to approved(frozen) while the version is frozen.

- .gitignore
- website/src/components/issues/GridColumns.js
- website/src/components/issues/filter/FilterDialog.js
- website/src/components/issues/renderer/PickTriage.js
This PR do follow things:
- Add Release Block filter on version triage plane.
- make void filter (-) take effect in filter dialog
- fix components sort function.
> fix( filter ): add Release Block filter && make void filter valid && fix components sort function.

- internal/service/version_triage_info.go
> fix(version triage): render default value of ReleaseVersionBlock.

- commons/utils/slice.go
- internal/dto/issue_relation_info.go
- internal/entity/issue.go
- internal/repository/issue.go
- internal/service/issue_relation_info_local.go
- website/src/components/issues/filter/FilterDialog.js
- website/src/pages/all.js
- website/src/pages/release.js
Issue Number: close #180 , #181
> feature( filter ): add components filter to 'all' plane && add end time of issue create time and issue close time.

- website/src/components/issues/GridColumns.js
- website/src/pages/release.js
> feature(frontend): add affected lower version

- website/src/components/issues/renderer/BlockRelease.js
> Feature(security)：add alert while users cancel block status

- internal/repository/issue.go
- internal/service/component/component_mapper.go
Issue Number: close #207 
Add component filter into issue sql.
> fix(filter): fix component filter in sql

- commons/utils/string.go
- commons/utils/string_test.go
- internal/dto/issue_relation_info.go
- internal/entity/README.md
- internal/entity/issue.go
- internal/entity/release_version.go
- internal/repository/issue_relation_info.go
- internal/repository/issue_relation_info_test.go
- internal/service/issue_relation_info_local.go
- website/src/components/issues/GridColumns.js
- website/src/components/issues/detail/IssueTriage.js
- website/src/components/issues/filter/FilterDialog.js
- website/src/pages/all.js
Issue Number: close #217 
- Add filter logic in the dal layer because of the counting requirements.
- Fix the logic bug of filtering affection info which should be apply to the issue entity.
> Feature(filter): add need triage filter to all issues page.

- commons/git/util.go
- commons/git/util_test.go
- internal/controller/feishu_handler/cmd_deliver.go
- internal/controller/feishu_handler/cmd_deliver_issue.go
- internal/controller/feishu_handler/handler_util.go
- internal/controller/version_triage_info.go
- internal/model/issue.go
- internal/model/issue_cmd.go
- internal/model/issue_cmd_test.go
- internal/model/issue_pr_relation.go
- internal/model/issue_service.go
- internal/model/pick_triage.go
- internal/model/pick_triage_trans.go
- internal/model/pull_request.go
- internal/model/version_triage.go
- internal/service/version_triage_info.go
- internal/service/version_triage_info_test.go
> feature: support force approve by chatops

- commons/database/mysql.go
- internal/controller/feishu_handler/msg_receiver.go
- internal/controller/hotfix.go
- internal/dto/hotfix.go
- internal/entity/hotfix.go
- internal/entity/hotfix_release_info.go
- internal/model/hotfix.go
- internal/model/hotfix_release_info.go
- internal/service/hotfix.go
- internal/service/webhook_pull_request.go
- internal/service/webhook_pull_request_test.go
- website/src/components/hotfix/BaseVersionSelector.js
- website/src/components/hotfix/HotfixAdd.js
- website/src/components/hotfix/HotfixAddBaseInfo.js
- website/src/components/hotfix/HotfixAddEnvInfo.js
- website/src/components/hotfix/HotfixAddPrecheck.js
- website/src/components/hotfix/HotfixAddReleaseInfo.js
- website/src/components/hotfix/HotfixReleaseItem.js
- Add & refactor hotfix apply page
- add precheck page.
- optimize apply page.
- Modify HotfixSaveRequest
- Add releaseInfos.
- Modify model.Hotfix
- Add artifactures for holding slice type artifact infos.
- Add releaseInfos for holding issue/pr models.
> [WIP] feature(hotfix): optimize hotfix apply page.

- internal/constants/feishu_msg_template.go
- internal/dto/hotfix.go
- internal/entity/hotfix.go
- internal/model/hotfix.go
- internal/model/hotfix_cmd.go
- internal/model/hotfix_release_info.go
- internal/model/hotfix_release_info_cmd.go
- internal/model/hotfix_status.go
- internal/model/hotfix_trans.go
- internal/model/hotfix_trans_help.go
- internal/repository/issue.go
- internal/repository/pull_request.go
- internal/service/hotfix.go
- internal/service/hotfix_dto_mapper.go
- internal/service/webhook_issue.go
- website/src/components/hotfix/HotfixAdd.js
- website/src/components/hotfix/HotfixAddBaseInfo.js
CRUD of hotfix:
- map hotfix model from request
- Select/Refresh issue/pr info in repository.
- Optimize pending approval message
- <img width="608" alt="image" src="https://user-images.githubusercontent.com/11363886/223909549-d1bc0021-f2d6-4237-90a2-d53024f96624.png">
- basic crud logic.
> feat(hotfix): CRUD of hotfix

- internal/dto/hotfix.go
- internal/entity/hotfix_release_info.go
- internal/service/hotfix.go
- internal/service/hotfix_dto_mapper.go
- website/src/components/hotfix/HotfixAdd.js
- website/src/components/hotfix/HotfixAddReleaseInfo.js
- website/src/components/hotfix/HotfixAddReleaseItem.js
- website/src/components/hotfix/HotfixTriage.js
- website/src/components/hotfix/HotfixTriageBaseInfo.js
- website/src/components/hotfix/HotfixTriageReleaseInfo.js
- website/src/components/hotfix/HotfixTriageReleaseItem.js
- website/src/components/hotfix/HotfixTriageStepper.js
- Add "All Prs Pushed" checkbox
- Make the triage update button valid.
- Make the triage stepper valid.
> feat(issue triage): optimize triage page
